import React from 'react'

export const code = <div className="javascript"><ol><li className="li1"><div className="de1"><span className="kw2">const</span> gcd <span className="sy0">=</span> <span className="br0">&#40;</span>a<span className="sy0">,</span> b<span className="br0">&#41;</span> <span className="sy0">=&gt;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="kw1">if</span> <span className="br0">&#40;</span>a <span className="sy0">===</span> b<span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="kw1">return</span> a</div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="br0">&#125;</span> <span className="kw1">else</span> <span className="kw1">if</span> <span className="br0">&#40;</span>a <span className="sy0">&gt;</span> b<span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li2"><div className="de2">&nbsp; &nbsp; &nbsp; <span className="kw1">return</span> gcd<span className="br0">&#40;</span>a <span className="sy0">-</span> b<span className="sy0">,</span> b<span className="br0">&#41;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; <span className="br0">&#125;</span> <span className="kw1">else</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; &nbsp; <span className="kw1">return</span> gcd<span className="br0">&#40;</span>a<span className="sy0">,</span> b<span className="sy0">-</span>a<span className="br0">&#41;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; &nbsp; <span className="br0">&#125;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="br0">&#125;</span></div></li>
    <li className="li2"><div className="de2">&nbsp; </div></li>
    <li className="li1"><div className="de1">&nbsp; gcd<span className="br0">&#40;</span><span className="nu0">8</span><span className="sy0">,</span><span className="nu0">5</span><span className="br0">&#41;</span></div></li>
</ol></div>

export const bubbleSort = <div className="javascript"><ol><li className="li1"><div className="de1"><span className="kw2">const</span> bubbleSort <span className="sy0">=</span> <span className="br0">&#40;</span>arr<span className="br0">&#41;</span> <span className="sy0">=&gt;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="kw1">for</span> <span className="br0">&#40;</span>let bypass <span className="sy0">=</span> <span className="nu0">1</span><span className="sy0">;</span> bypass <span className="sy0">&lt;</span> arr.<span className="me1">length</span><span className="sy0">;</span> bypass <span className="sy0">+=</span> <span className="nu0">1</span><span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="kw1">for</span> <span className="br0">&#40;</span>let k <span className="sy0">=</span> <span className="nu0">0</span><span className="sy0">;</span> k <span className="sy0">&lt;</span> arr.<span className="me1">length</span> <span className="sy0">-</span> bypass<span className="sy0">;</span> k <span className="sy0">+=</span> <span className="nu0">1</span><span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; <span className="kw1">if</span> <span className="br0">&#40;</span>arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span> <span className="sy0">&gt;</span> arr<span className="br0">&#91;</span>k <span className="sy0">+</span> <span className="nu0">1</span><span className="br0">&#93;</span><span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li2"><div className="de2">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span className="br0">&#91;</span>arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span><span className="sy0">,</span> arr<span className="br0">&#91;</span>k <span className="sy0"></span> + <span className="nu0">1</span><span className="br0">&#93;</span><span className="br0">&#93;</span> <span className="sy0">=</span> <span className="br0">&#91;</span>arr<span className="br0">&#91;</span>k <span className="sy0"></span> + <span className="nu0">1</span><span className="br0">&#93;</span><span className="sy0">,</span> arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span><span className="br0">&#93;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; &nbsp; <span className="br0">&#125;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; <span className="br0">&#125;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="br0">&#125;</span> <span className="kw1">return</span> arr</div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="br0">&#125;</span><span className="sy0">;</span></div></li>
    <li className="li2"><div className="de2"><span className="kw2">const</span> arrTest <span className="sy0">=</span> <span className="br0">&#91;</span><span className="nu0">3</span><span className="sy0">,</span> <span className="nu0">2</span><span className="sy0">,</span> <span className="nu0">10</span><span className="sy0">,</span> <span className="sy0">-</span><span className="nu0">2</span><span className="sy0">,</span> <span className="nu0">0</span><span className="br0">&#93;</span></div></li>
    <li className="li1"><div className="de1">bubble<span className="br0">&#40;</span>arrTest<span className="br0">&#41;</span></div></li>
</ol></div>

export const insertionSorting = <div className="javascript"><ol><li className="li1"><div className="de1"><span className="kw2">const</span> insert <span className="sy0">=</span> <span className="br0">&#40;</span>arr<span className="br0">&#41;</span> <span className="sy0">=&gt;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="kw1">for</span> <span className="br0">&#40;</span>let top <span className="sy0">=</span> <span className="nu0">1</span><span className="sy0">;</span> top <span className="sy0">&lt;</span> arr.<span className="me1">length</span><span className="sy0">;</span> top <span className="sy0">+=</span> <span className="nu0">1</span><span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; let k <span className="sy0">=</span> top</div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="kw1">while</span> <span className="br0">&#40;</span>k <span className="sy0">&gt;</span> <span className="nu0">0</span> <span className="sy0">&amp;&amp;</span> arr<span className="br0">&#91;</span>k <span className="sy0">-</span> <span className="nu0">1</span><span className="br0">&#93;</span> <span className="sy0">&gt;</span> arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span><span className="br0">&#41;</span> <span className="br0">&#123;</span></div></li>
    <li className="li2"><div className="de2">&nbsp; &nbsp; &nbsp; <span className="br0">&#91;</span>arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span><span className="sy0">,</span> arr<span className="br0">&#91;</span>k <span className="sy0">-</span> <span className="nu0">1</span><span className="br0">&#93;</span><span className="br0">&#93;</span> <span className="sy0">=</span> <span className="br0">&#91;</span>arr<span className="br0">&#91;</span>k <span className="sy0">-</span> <span className="nu0">1</span><span className="br0">&#93;</span><span className="sy0">,</span> arr<span className="br0">&#91;</span>k<span className="br0">&#93;</span><span className="br0">&#93;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; k <span className="sy0">-=</span> <span className="nu0">1</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; &nbsp; <span className="br0">&#125;</span></div></li>
    <li className="li1"><div className="de1">&nbsp; &nbsp; <span className="br0">&#125;</span> <span className="kw1">return</span> arr</div></li>
    <li className="li1"><div className="de1">&nbsp; <span className="br0">&#125;</span><span className="sy0">;</span></div></li>
    <li className="li2"><div className="de2"><span className="kw2">const</span> arrTest <span className="sy0">=</span> <span className="br0">&#91;</span><span className="nu0">2</span><span className="sy0">,</span> <span className="nu0">4</span><span className="sy0">,</span> <span className="nu0">1</span><span className="sy0">,</span> <span className="nu0">5</span><span className="sy0">,</span> <span className="nu0">3</span><span className="br0">&#93;</span></div></li>
    <li className="li1"><div className="de1">insert<span className="br0">&#40;</span>arrTest<span className="br0">&#41;</span></div></li>
    </ol></div>